# Generated by Django 4.2.1 on 2023-05-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_etudiant_cne_alter_etudiant_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='CNE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneebac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
