# Generated by Django 4.2.1 on 2023-05-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_etudiant_cne_alter_etudiant_anneebac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='CIN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='salaire',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
