# Generated by Django 4.2.1 on 2023-05-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_professeur_cin_alter_professeur_salaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
