# Generated by Django 4.2.1 on 2023-05-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin1',
        ),
    ]
