# Generated by Django 4.2.1 on 2023-06-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_classe_option_remove_admin1_id_remove_etudiant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='option',
            new_name='option1',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='CNE',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
