# Generated by Django 4.2.1 on 2023-06-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_etudiant_option1'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='option1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.option'),
            preserve_default=False,
        ),
    ]
