# Generated by Django 4.2.1 on 2023-06-01 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_etudiant_option1'),
    ]

    operations = [
        migrations.CreateModel(
            name='salle',
            fields=[
                ('num_salle', models.IntegerField(primary_key=True, serialize=False)),
                ('nplace', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='classe',
            name='nplace',
        ),
        migrations.CreateModel(
            name='profsalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.IntegerField()),
                ('CIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.professeur')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours')),
                ('num_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.salle')),
            ],
        ),
    ]
