# Generated by Django 4.2.1 on 2023-06-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professeur',
            old_name='matiere',
            new_name='sexe',
        ),
    ]
