# Generated by Django 4.2.1 on 2023-06-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_note_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant1',
            fields=[
                ('CNE1', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('nom1', models.CharField(max_length=100)),
                ('prenom1', models.CharField(max_length=100)),
                ('sexe1', models.CharField(choices=[(' homme', 'homme'), ('femme', 'femme')], max_length=10)),
                ('tel1', models.IntegerField()),
                ('email1', models.CharField(max_length=100)),
                ('adresse1', models.CharField(max_length=100)),
                ('anneebac1', models.IntegerField()),
                ('classe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.classe')),
                ('option11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.option')),
            ],
        ),
    ]
