# Generated by Django 4.2.1 on 2023-06-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_etudiant1'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant1',
            name='status',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
    ]
