# Generated by Django 4.2.1 on 2023-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_etudiant1_parcours1'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='n_etude',
            field=models.CharField(choices=[(' Premiere annee', ' Premiere annee'), (' Deuxieme annee', ' Deuxieme annee'), (' Troisieme annee', ' Troisieme annee'), (' Quatrieme annee', ' Quatrieme annee'), (' Cinquieme annee', ' Cinquieme annee')], default='Premiere annee', max_length=40),
            preserve_default=False,
        ),
    ]
