# Generated by Django 4.2.1 on 2023-07-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_classe_n_etude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.module'),
            preserve_default=False,
        ),
    ]
