# Generated by Django 4.2.1 on 2023-07-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_remove_emp_id_alter_emp_num_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='cours3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='cours4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='cours5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='cours6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='prof3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='prof4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='prof5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='prof6',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
