# Generated by Django 4.2.1 on 2023-07-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_emp_cours3_emp_cours4_emp_cours5_emp_cours6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('num_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.classe')),
                ('num_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours')),
                ('num_et', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='enote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('num_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.classe')),
                ('num_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours')),
                ('num_et', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
            ],
        ),
    ]
