# Generated by Django 4.2.1 on 2023-07-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_notemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='smodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.module')),
            ],
        ),
    ]
