# Generated by Django 4.2.1 on 2023-07-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_notemodule_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodule',
            name='module',
        ),
    ]
