# Generated by Django 4.2.1 on 2023-07-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_remove_notemodule_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodule',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.module'),
            preserve_default=False,
        ),
    ]
