# Generated by Django 4.2.1 on 2023-07-09 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_remove_note_id_alter_note_num_et'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='num_et',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='enote',
            unique_together={('num_et', 'num_cours')},
        ),
        migrations.AlterUniqueTogether(
            name='notec2',
            unique_together={('num_et', 'num_cours')},
        ),
    ]
