# Generated by Django 4.2.1 on 2023-07-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_note_id_alter_note_num_et_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enote',
            name='id',
        ),
        migrations.AlterField(
            model_name='enote',
            name='num_cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.cours'),
        ),
    ]
