# Generated by Django 4.2.1 on 2023-07-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_remove_enote_id_alter_enote_num_cours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AddField(
            model_name='enote',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enote',
            name='num_cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours'),
        ),
        migrations.AlterField(
            model_name='note',
            name='num_et',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.etudiant'),
        ),
    ]
