# Generated by Django 4.2.1 on 2023-07-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_alter_note_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='num_cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours'),
        ),
    ]
