# Generated by Django 4.2.1 on 2023-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0043_gmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
